sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
  - type: npm
    path: extension/package.json
version:
  fromSource: pom.xml
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: true
  exasolDbVersions:
    - "8.24.0"
    - "7.1.26"
excludes:
  - "E-PK-CORE-17: Missing required file: 'release_config.yml'"
