sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
version:
  fromSource: pom.xml
build:
  # Using large runner to avoid out-of-memory errors during integration tests:
  # - ETL-4101: Inserting data failed with error 'Query terminated because system running out of memory.'
  # - Connection lost after system running out of memory
  runnerOs: int-linux-x64-8core-ubuntu24.04-1
  freeDiskSpace: true
  exasolDbVersions:
   - "2026.1.0"
   - "2025.1.13"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix VM Crash in UDFs
            id: fix-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        - action: INSERT_AFTER
          job: matrix-build
          stepId: build-pk-verify
          content:
            name: Collect DB logs
            if: ${{ always() }}
            id: collect-db-logs
            run: |
              df -h
              docker ps
              CONTAINER_NAME=$(docker ps --filter "ancestor=exasol/docker-db:${{ matrix.exasol_db_version }}" --format "{{.Names}}")
              mkdir -p /tmp/db-log/
              docker cp "$CONTAINER_NAME:/exa/logs/" /tmp/db-log/

        - action: INSERT_AFTER
          job: matrix-build
          stepId: collect-db-logs
          content:
            name: Upload DB logs
            if: ${{ always() }}
            id: upload-db-logs
            uses: actions/upload-artifact@v7
            with:
              path: /tmp/db-log/
              name: exasol-db-log-${{ matrix.exasol_db_version }}
              retention-days: 3
              if-no-files-found: error
