sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
  - type: npm
    path: extension/package.json
    artifacts:
      - dist/oracle-vs-extension.js
version:
  fromSource: pom.xml
build:
  # Using large runner to avoid out-of-memory errors during integration tests:
  # - ETL-4101: Inserting data failed with error 'Query terminated because system running out of memory.'
  # - Connection lost after system running out of memory
  runnerOs: int-linux-x64-8core-ubuntu24.04-1
  freeDiskSpace: true
  exasolDbVersions:
   - "2025.2.1"
   - "2025.1.10"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix VM Crash in UDFs
            id: fix-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
